require('newUser/newUser-component');
require('customerPage/customerPage-component');
require('accountInformation/accountInformation-component');
require('operatorPage/operatorPage-component');
require('operatorPage/CollapseDemoCtrl');
require('missionsPage/missionsPage-component');
require('missionsPage/missionDetailsComponent');
require('adminPage/adminPage-component');
require('userList/userList_component');
